sudo: false

language: rust
cache: cargo

rust:
    - stable
    - beta
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly

script:
    - cargo test --all
    - cargo test --all --features native-tls
