[package]
name = "amiquip"
version = "0.1.0"
authors = ["John Gallagher <johnkgallagher@gmail.com>"]
edition = "2018"
build = "build.rs"

[features]

[dependencies]
failure = "0.1"
input_buffer = "0.2"
bytes = "0.4"
amq-protocol = "1.4"
log = "0.4"
mio = "0.6"
mio-extras = "2.0"
cookie-factory = "0.2"
crossbeam-channel = "0.3"
indexmap = "1.0"
url = "1.7"
native-tls = { version = "*", optional = true }

# only for test binary - remove later
env_logger = "0.6"

[build-dependencies]
built = "0.3"

[dev-dependencies]
mockstream = "0.0.3"
